### ISSUE TITLE
filetype detectation

### ISSUE THREAD

**Issue by tani** [rbtnn/go-wandbox#2]
Thanks for awesome tool.
Cloud you add language detection like [this](https://github.com/ta2gch/wcc), it's forked from your repository (it has my kind of short options and short command :smile: .)

Cheers.

**Comment by rbtnn** [comment]
> Cloud you add language detection like this

@ta2gch Okey, I will add language detection.

**Comment by rbtnn** [comment]
@ta2gch I have just added language detection. Please check [this commit](https://github.com/rbtnn/go-wandbox/commit/c0aa700d9358cc44158595be418b240152e89569).

**Comment by tani** [comment]
Thank you so much!
